version: "3.9"

services:
  gitea:
    image: gitea/gitea:1.22
    container_name: gitea
    restart: always
    environment:
      USER_UID: 1000
      USER_GID: 1000
      GITEA__database__DB_TYPE: sqlite3
      GITEA__database__PATH: /data/gitea/gitea.db
      GITEA__server__DOMAIN: gitea
      GITEA__server__ROOT_URL: http://gitea:3000/
      GITEA__server__SSH_PORT: 2222
      GITEA__server__SSH_LISTEN_PORT: 2222
      GITEA__server__DISABLE_SSH: false
      GITEA__server__START_SSH_SERVER: true
      GITEA__security__INSTALL_LOCK: true
      GITEA__service__DISABLE_REGISTRATION: true
      GITEA_ADMIN_USER: gitadmin
      GITEA_ADMIN_PASSWORD: gitadmin123
      GITEA_ADMIN_EMAIL: gitadmin@gitea.local
      GITEA__security__SECRET_KEY: supersecret
    volumes:
      - ./data/gitea:/data
      - ./scripts/init_gitea.sh:/docker-entrypoint-init.d/init_gitea.sh
      - ./ssh_keys:/etc/ssh_keys
    ports:
      - "3000:3000"
      - "2222:2222" 
      - "9418:9418"   # git:// protocol
    networks:
      gitnet:
        aliases:
          - gitea

  tester:
    build:
      context: .
      dockerfile: docker/tester/Dockerfile
    container_name: tester
    depends_on:
      - gitea
    environment:
      GITEA_BASE_URL: http://gitea:3000
      GITEA_SSH_HOST: gitea
      GITEA_SSH_PORT: 2222
      GITEA_ADMIN_USER: gitadmin
      GITEA_ADMIN_PASSWORD: gitadmin123
      GITEA_ADMIN_EMAIL: gitadmin@gitea.local
      GITEA_ADMIN_TOKEN_FILE: /data/gitea_admin_token
      PYTHONPATH: /app
    volumes:
      - ./tests:/app/tests
      - ./allure-results:/app/allure-results
      - ./ssh_keys:/root/.ssh
    networks:
      - gitnet

networks:
  gitnet:
    driver: bridge
